"""add phone_hash to user

Revision ID: 0ac89fbf9233
Revises: 12597c285a72
Create Date: 2026-03-26 23:12:48.106729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac89fbf9233'
down_revision: Union[str, None] = '12597c285a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_phone_hash'), 'users', ['phone_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_hash'), table_name='users')
    op.drop_column('users', 'phone_hash')
    # ### end Alembic commands ###
