"""initial user roles

Revision ID: 12597c285a72
Revises: 
Create Date: 2026-03-26 22:35:33.549158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12597c285a72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'doctor', 'asha_worker', 'migrant_worker', name='userrole'), nullable=False),
    sa.Column('swasthya_id', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_encrypted', sa.String(length=1024), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('blood_type', sa.String(length=8), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('current_medications', sa.JSON(), nullable=False),
    sa.Column('recent_diagnoses', sa.JSON(), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('consent_granted', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_swasthya_id'), 'users', ['swasthya_id'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('original_path', sa.String(length=512), nullable=False),
    sa.Column('parsed_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_worker_id'), 'documents', ['worker_id'], unique=False)
    op.create_table('health_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('record_type', sa.String(length=64), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_records_record_type'), 'health_records', ['record_type'], unique=False)
    op.create_index(op.f('ix_health_records_worker_id'), 'health_records', ['worker_id'], unique=False)
    op.create_table('location_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.String(length=32), nullable=True),
    sa.Column('longitude', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_logs_created_at'), 'location_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_location_logs_worker_id'), 'location_logs', ['worker_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_channel'), 'notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_worker_id'), 'notifications', ['worker_id'], unique=False)
    op.create_table('risk_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('occupation', sa.String(length=128), nullable=False),
    sa.Column('tasks_json', sa.JSON(), nullable=False),
    sa.Column('symptoms_json', sa.JSON(), nullable=False),
    sa.Column('years_in_job', sa.Integer(), nullable=False),
    sa.Column('scores_json', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_profiles_risk_level'), 'risk_profiles', ['risk_level'], unique=False)
    op.create_index(op.f('ix_risk_profiles_worker_id'), 'risk_profiles', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_profiles_worker_id'), table_name='risk_profiles')
    op.drop_index(op.f('ix_risk_profiles_risk_level'), table_name='risk_profiles')
    op.drop_table('risk_profiles')
    op.drop_index(op.f('ix_notifications_worker_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_channel'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_location_logs_worker_id'), table_name='location_logs')
    op.drop_index(op.f('ix_location_logs_created_at'), table_name='location_logs')
    op.drop_table('location_logs')
    op.drop_index(op.f('ix_health_records_worker_id'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_record_type'), table_name='health_records')
    op.drop_table('health_records')
    op.drop_index(op.f('ix_documents_worker_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_swasthya_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
